name: Sed-replacer
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "LEGENDBOT"
          replace: "FIREXUSERBOT"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'SeD Replacer'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: TeamEviral
          commit_user_email: dxpubg61@gmail.com
          commit_author: TeamEviral <dxpubg61@gmail.com>
